"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023 LiveKit, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
from . import livekit_egress_pb2
from . import livekit_ingress_pb2
from . import livekit_models_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class WebhookEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_FIELD_NUMBER: builtins.int
    ROOM_FIELD_NUMBER: builtins.int
    PARTICIPANT_FIELD_NUMBER: builtins.int
    EGRESS_INFO_FIELD_NUMBER: builtins.int
    INGRESS_INFO_FIELD_NUMBER: builtins.int
    TRACK_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    NUM_DROPPED_FIELD_NUMBER: builtins.int
    event: builtins.str
    """one of room_started, room_finished, participant_joined, participant_left,
    track_published, track_unpublished, egress_started, egress_updated, egress_ended,
    ingress_started, ingress_ended
    """
    @property
    def room(self) -> livekit_models_pb2.Room: ...
    @property
    def participant(self) -> livekit_models_pb2.ParticipantInfo:
        """set when event is participant_* or track_*"""
    @property
    def egress_info(self) -> livekit_egress_pb2.EgressInfo:
        """set when event is egress_*"""
    @property
    def ingress_info(self) -> livekit_ingress_pb2.IngressInfo:
        """set when event is ingress_*"""
    @property
    def track(self) -> livekit_models_pb2.TrackInfo:
        """set when event is track_*"""
    id: builtins.str
    """unique event uuid"""
    created_at: builtins.int
    """timestamp in seconds"""
    num_dropped: builtins.int
    def __init__(
        self,
        *,
        event: builtins.str = ...,
        room: livekit_models_pb2.Room | None = ...,
        participant: livekit_models_pb2.ParticipantInfo | None = ...,
        egress_info: livekit_egress_pb2.EgressInfo | None = ...,
        ingress_info: livekit_ingress_pb2.IngressInfo | None = ...,
        track: livekit_models_pb2.TrackInfo | None = ...,
        id: builtins.str = ...,
        created_at: builtins.int = ...,
        num_dropped: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["egress_info", b"egress_info", "ingress_info", b"ingress_info", "participant", b"participant", "room", b"room", "track", b"track"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created_at", b"created_at", "egress_info", b"egress_info", "event", b"event", "id", b"id", "ingress_info", b"ingress_info", "num_dropped", b"num_dropped", "participant", b"participant", "room", b"room", "track", b"track"]) -> None: ...

global___WebhookEvent = WebhookEvent
