"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 LiveKit, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _VideoQuality:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _VideoQualityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_VideoQuality.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    VIDEO_QUALITY_LOW: _VideoQuality.ValueType  # 0
    VIDEO_QUALITY_MEDIUM: _VideoQuality.ValueType  # 1
    VIDEO_QUALITY_HIGH: _VideoQuality.ValueType  # 2

class VideoQuality(_VideoQuality, metaclass=_VideoQualityEnumTypeWrapper):
    """Video quality for simulcasted tracks."""

VIDEO_QUALITY_LOW: VideoQuality.ValueType  # 0
VIDEO_QUALITY_MEDIUM: VideoQuality.ValueType  # 1
VIDEO_QUALITY_HIGH: VideoQuality.ValueType  # 2
Global___VideoQuality: _TypeAlias = VideoQuality  # noqa: Y015

@_typing.final
class EnableRemoteTrackPublicationRequest(_message.Message):
    """Enable/Disable a remote track publication"""

    DESCRIPTOR: _descriptor.Descriptor

    TRACK_PUBLICATION_HANDLE_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    track_publication_handle: _builtins.int
    enabled: _builtins.bool
    def __init__(
        self,
        *,
        track_publication_handle: _builtins.int | None = ...,
        enabled: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "track_publication_handle", b"track_publication_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "track_publication_handle", b"track_publication_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EnableRemoteTrackPublicationRequest: _TypeAlias = EnableRemoteTrackPublicationRequest  # noqa: Y015

@_typing.final
class EnableRemoteTrackPublicationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___EnableRemoteTrackPublicationResponse: _TypeAlias = EnableRemoteTrackPublicationResponse  # noqa: Y015

@_typing.final
class UpdateRemoteTrackPublicationDimensionRequest(_message.Message):
    """update a remote track publication dimension"""

    DESCRIPTOR: _descriptor.Descriptor

    TRACK_PUBLICATION_HANDLE_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    track_publication_handle: _builtins.int
    width: _builtins.int
    height: _builtins.int
    def __init__(
        self,
        *,
        track_publication_handle: _builtins.int | None = ...,
        width: _builtins.int | None = ...,
        height: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "track_publication_handle", b"track_publication_handle", "width", b"width"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "track_publication_handle", b"track_publication_handle", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateRemoteTrackPublicationDimensionRequest: _TypeAlias = UpdateRemoteTrackPublicationDimensionRequest  # noqa: Y015

@_typing.final
class UpdateRemoteTrackPublicationDimensionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___UpdateRemoteTrackPublicationDimensionResponse: _TypeAlias = UpdateRemoteTrackPublicationDimensionResponse  # noqa: Y015

@_typing.final
class SetRemoteTrackPublicationQualityRequest(_message.Message):
    """For tracks that support simulcasting, adjust subscribed quality."""

    DESCRIPTOR: _descriptor.Descriptor

    TRACK_PUBLICATION_HANDLE_FIELD_NUMBER: _builtins.int
    QUALITY_FIELD_NUMBER: _builtins.int
    track_publication_handle: _builtins.int
    quality: Global___VideoQuality.ValueType
    def __init__(
        self,
        *,
        track_publication_handle: _builtins.int | None = ...,
        quality: Global___VideoQuality.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["quality", b"quality", "track_publication_handle", b"track_publication_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["quality", b"quality", "track_publication_handle", b"track_publication_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetRemoteTrackPublicationQualityRequest: _TypeAlias = SetRemoteTrackPublicationQualityRequest  # noqa: Y015

@_typing.final
class SetRemoteTrackPublicationQualityResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___SetRemoteTrackPublicationQualityResponse: _TypeAlias = SetRemoteTrackPublicationQualityResponse  # noqa: Y015
