"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023 LiveKit, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _EncryptionType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EncryptionTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EncryptionType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Gcm: _EncryptionType.ValueType  # 1
    Custom: _EncryptionType.ValueType  # 2

class EncryptionType(_EncryptionType, metaclass=_EncryptionTypeEnumTypeWrapper): ...

Gcm: EncryptionType.ValueType  # 1
Custom: EncryptionType.ValueType  # 2
global___EncryptionType = EncryptionType

class _E2EEState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _E2EEStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_E2EEState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NEW: _E2EEState.ValueType  # 0
    OK: _E2EEState.ValueType  # 1
    ENCRYPTION_FAILED: _E2EEState.ValueType  # 2
    DECRYPTION_FAILED: _E2EEState.ValueType  # 3
    MISSING_KEY: _E2EEState.ValueType  # 4
    KEY_RATCHETED: _E2EEState.ValueType  # 5
    INTERNAL_ERROR: _E2EEState.ValueType  # 6

class E2EEState(_E2EEState, metaclass=_E2EEStateEnumTypeWrapper): ...

NEW: E2EEState.ValueType  # 0
OK: E2EEState.ValueType  # 1
ENCRYPTION_FAILED: E2EEState.ValueType  # 2
DECRYPTION_FAILED: E2EEState.ValueType  # 3
MISSING_KEY: E2EEState.ValueType  # 4
KEY_RATCHETED: E2EEState.ValueType  # 5
INTERNAL_ERROR: E2EEState.ValueType  # 6
global___E2EEState = E2EEState

@typing_extensions.final
class KeyProviderOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RATCHET_WINDOW_SIZE_FIELD_NUMBER: builtins.int
    RATCHET_SALT_FIELD_NUMBER: builtins.int
    UNCRYPTED_MAGIC_BYTES_FIELD_NUMBER: builtins.int
    ratchet_window_size: builtins.int
    ratchet_salt: builtins.bytes
    uncrypted_magic_bytes: builtins.bytes
    def __init__(
        self,
        *,
        ratchet_window_size: builtins.int = ...,
        ratchet_salt: builtins.bytes = ...,
        uncrypted_magic_bytes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ratchet_salt", b"ratchet_salt", "ratchet_window_size", b"ratchet_window_size", "uncrypted_magic_bytes", b"uncrypted_magic_bytes"]) -> None: ...

global___KeyProviderOptions = KeyProviderOptions

@typing_extensions.final
class E2EEOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENABLED_FIELD_NUMBER: builtins.int
    IS_SHARED_KEY_FIELD_NUMBER: builtins.int
    SHARED_KEY_FIELD_NUMBER: builtins.int
    KEY_PROVIDER_OPTIONS_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    is_shared_key: builtins.bool
    shared_key: builtins.str
    @property
    def key_provider_options(self) -> global___KeyProviderOptions: ...
    def __init__(
        self,
        *,
        enabled: builtins.bool = ...,
        is_shared_key: builtins.bool = ...,
        shared_key: builtins.str = ...,
        key_provider_options: global___KeyProviderOptions | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["key_provider_options", b"key_provider_options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["enabled", b"enabled", "is_shared_key", b"is_shared_key", "key_provider_options", b"key_provider_options", "shared_key", b"shared_key"]) -> None: ...

global___E2EEOptions = E2EEOptions

@typing_extensions.final
class E2EEManagerSetEnabledRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    room_handle: builtins.int
    enabled: builtins.bool
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
        room_handle: builtins.int = ...,
        enabled: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id", "enabled", b"enabled", "room_handle", b"room_handle"]) -> None: ...

global___E2EEManagerSetEnabledRequest = E2EEManagerSetEnabledRequest

@typing_extensions.final
class E2EEManagerSetEnabledResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> None: ...

global___E2EEManagerSetEnabledResponse = E2EEManagerSetEnabledResponse

@typing_extensions.final
class E2EEManagerSetSharedKeyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    ENABLE_SHARED_KEY_FIELD_NUMBER: builtins.int
    SHARED_KEY_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    room_handle: builtins.int
    enable_shared_key: builtins.bool
    shared_key: builtins.str
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
        room_handle: builtins.int = ...,
        enable_shared_key: builtins.bool = ...,
        shared_key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id", "enable_shared_key", b"enable_shared_key", "room_handle", b"room_handle", "shared_key", b"shared_key"]) -> None: ...

global___E2EEManagerSetSharedKeyRequest = E2EEManagerSetSharedKeyRequest

@typing_extensions.final
class E2EEManagerSetSharedKeyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> None: ...

global___E2EEManagerSetSharedKeyResponse = E2EEManagerSetSharedKeyResponse

@typing_extensions.final
class E2EEManagerGetFrameCryptorsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    room_handle: builtins.int
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
        room_handle: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id", "room_handle", b"room_handle"]) -> None: ...

global___E2EEManagerGetFrameCryptorsRequest = E2EEManagerGetFrameCryptorsRequest

@typing_extensions.final
class FrameCryptor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_ID_FIELD_NUMBER: builtins.int
    ENCRYPTION_TYPE_FIELD_NUMBER: builtins.int
    KEY_INDEX_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    participant_id: builtins.str
    encryption_type: global___EncryptionType.ValueType
    key_index: builtins.int
    enabled: builtins.bool
    def __init__(
        self,
        *,
        participant_id: builtins.str = ...,
        encryption_type: global___EncryptionType.ValueType = ...,
        key_index: builtins.int = ...,
        enabled: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["enabled", b"enabled", "encryption_type", b"encryption_type", "key_index", b"key_index", "participant_id", b"participant_id"]) -> None: ...

global___FrameCryptor = FrameCryptor

@typing_extensions.final
class E2EEManagerGetFrameCryptorsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    FRAME_CRYPTORS_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    @property
    def frame_cryptors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FrameCryptor]: ...
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
        frame_cryptors: collections.abc.Iterable[global___FrameCryptor] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id", "frame_cryptors", b"frame_cryptors"]) -> None: ...

global___E2EEManagerGetFrameCryptorsResponse = E2EEManagerGetFrameCryptorsResponse

@typing_extensions.final
class FrameCryptorSetEnabledRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    PARTICIPANT_ID_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    room_handle: builtins.int
    participant_id: builtins.str
    enabled: builtins.bool
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
        room_handle: builtins.int = ...,
        participant_id: builtins.str = ...,
        enabled: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id", "enabled", b"enabled", "participant_id", b"participant_id", "room_handle", b"room_handle"]) -> None: ...

global___FrameCryptorSetEnabledRequest = FrameCryptorSetEnabledRequest

@typing_extensions.final
class FrameCryptorSetEnabledResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> None: ...

global___FrameCryptorSetEnabledResponse = FrameCryptorSetEnabledResponse

@typing_extensions.final
class KeyProviderSetKeyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    PARTICIPANT_ID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    KEY_INDEX_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    room_handle: builtins.int
    participant_id: builtins.str
    key: builtins.str
    key_index: builtins.int
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
        room_handle: builtins.int = ...,
        participant_id: builtins.str = ...,
        key: builtins.str = ...,
        key_index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id", "key", b"key", "key_index", b"key_index", "participant_id", b"participant_id", "room_handle", b"room_handle"]) -> None: ...

global___KeyProviderSetKeyRequest = KeyProviderSetKeyRequest

@typing_extensions.final
class KeyProviderSetKeyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> None: ...

global___KeyProviderSetKeyResponse = KeyProviderSetKeyResponse

@typing_extensions.final
class KeyProviderRachetKeyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    PARTICIPANT_ID_FIELD_NUMBER: builtins.int
    KEY_INDEX_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    room_handle: builtins.int
    participant_id: builtins.str
    key_index: builtins.int
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
        room_handle: builtins.int = ...,
        participant_id: builtins.str = ...,
        key_index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id", "key_index", b"key_index", "participant_id", b"participant_id", "room_handle", b"room_handle"]) -> None: ...

global___KeyProviderRachetKeyRequest = KeyProviderRachetKeyRequest

@typing_extensions.final
class KeyProviderRachetKeyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    NEW_KEY_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    new_key: builtins.bytes
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
        new_key: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id", "new_key", b"new_key"]) -> None: ...

global___KeyProviderRachetKeyResponse = KeyProviderRachetKeyResponse

@typing_extensions.final
class KeyProviderExportKeyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    PARTICIPANT_ID_FIELD_NUMBER: builtins.int
    KEY_INDEX_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    room_handle: builtins.int
    participant_id: builtins.str
    key_index: builtins.int
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
        room_handle: builtins.int = ...,
        participant_id: builtins.str = ...,
        key_index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id", "key_index", b"key_index", "participant_id", b"participant_id", "room_handle", b"room_handle"]) -> None: ...

global___KeyProviderExportKeyRequest = KeyProviderExportKeyRequest

@typing_extensions.final
class KeyProviderExportKeyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    async_id: builtins.int
    key: builtins.bytes
    def __init__(
        self,
        *,
        async_id: builtins.int = ...,
        key: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id", "key", b"key"]) -> None: ...

global___KeyProviderExportKeyResponse = KeyProviderExportKeyResponse

@typing_extensions.final
class E2EERequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    E2EE_MANAGER_SET_ENABLED_FIELD_NUMBER: builtins.int
    E2EE_MANAGER_SET_SHARED_KEY_FIELD_NUMBER: builtins.int
    E2EE_MANAGER_GET_FRAME_CRYPTORS_FIELD_NUMBER: builtins.int
    FRAME_CRYPTOR_SET_ENABLED_FIELD_NUMBER: builtins.int
    KEY_PROVIDER_SET_KEY_FIELD_NUMBER: builtins.int
    KEY_PROVIDER_RACHET_KEY_FIELD_NUMBER: builtins.int
    KEY_PROVIDER_EXPORT_KEY_FIELD_NUMBER: builtins.int
    @property
    def e2ee_manager_set_enabled(self) -> global___E2EEManagerSetEnabledRequest: ...
    @property
    def e2ee_manager_set_shared_key(self) -> global___E2EEManagerSetSharedKeyRequest: ...
    @property
    def e2ee_manager_get_frame_cryptors(self) -> global___E2EEManagerGetFrameCryptorsRequest: ...
    @property
    def frame_cryptor_set_enabled(self) -> global___FrameCryptorSetEnabledRequest: ...
    @property
    def key_provider_set_key(self) -> global___KeyProviderSetKeyRequest: ...
    @property
    def key_provider_rachet_key(self) -> global___KeyProviderRachetKeyRequest: ...
    @property
    def key_provider_export_key(self) -> global___KeyProviderExportKeyRequest: ...
    def __init__(
        self,
        *,
        e2ee_manager_set_enabled: global___E2EEManagerSetEnabledRequest | None = ...,
        e2ee_manager_set_shared_key: global___E2EEManagerSetSharedKeyRequest | None = ...,
        e2ee_manager_get_frame_cryptors: global___E2EEManagerGetFrameCryptorsRequest | None = ...,
        frame_cryptor_set_enabled: global___FrameCryptorSetEnabledRequest | None = ...,
        key_provider_set_key: global___KeyProviderSetKeyRequest | None = ...,
        key_provider_rachet_key: global___KeyProviderRachetKeyRequest | None = ...,
        key_provider_export_key: global___KeyProviderExportKeyRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["e2ee_manager_get_frame_cryptors", b"e2ee_manager_get_frame_cryptors", "e2ee_manager_set_enabled", b"e2ee_manager_set_enabled", "e2ee_manager_set_shared_key", b"e2ee_manager_set_shared_key", "frame_cryptor_set_enabled", b"frame_cryptor_set_enabled", "key_provider_export_key", b"key_provider_export_key", "key_provider_rachet_key", b"key_provider_rachet_key", "key_provider_set_key", b"key_provider_set_key", "message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["e2ee_manager_get_frame_cryptors", b"e2ee_manager_get_frame_cryptors", "e2ee_manager_set_enabled", b"e2ee_manager_set_enabled", "e2ee_manager_set_shared_key", b"e2ee_manager_set_shared_key", "frame_cryptor_set_enabled", b"frame_cryptor_set_enabled", "key_provider_export_key", b"key_provider_export_key", "key_provider_rachet_key", b"key_provider_rachet_key", "key_provider_set_key", b"key_provider_set_key", "message", b"message"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["message", b"message"]) -> typing_extensions.Literal["e2ee_manager_set_enabled", "e2ee_manager_set_shared_key", "e2ee_manager_get_frame_cryptors", "frame_cryptor_set_enabled", "key_provider_set_key", "key_provider_rachet_key", "key_provider_export_key"] | None: ...

global___E2EERequest = E2EERequest

@typing_extensions.final
class E2EEResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    E2EE_MANAGER_SET_ENABLED_FIELD_NUMBER: builtins.int
    E2EE_MANAGER_SET_SHARED_KEY_FIELD_NUMBER: builtins.int
    E2EE_MANAGER_GET_FRAME_CRYPTORS_FIELD_NUMBER: builtins.int
    FRAME_CRYPTOR_SET_ENABLED_FIELD_NUMBER: builtins.int
    KEY_PROVIDER_SET_KEY_FIELD_NUMBER: builtins.int
    KEY_PROVIDER_RACHET_KEY_FIELD_NUMBER: builtins.int
    KEY_PROVIDER_EXPORT_KEY_FIELD_NUMBER: builtins.int
    @property
    def e2ee_manager_set_enabled(self) -> global___E2EEManagerSetEnabledResponse: ...
    @property
    def e2ee_manager_set_shared_key(self) -> global___E2EEManagerSetSharedKeyResponse: ...
    @property
    def e2ee_manager_get_frame_cryptors(self) -> global___E2EEManagerGetFrameCryptorsResponse: ...
    @property
    def frame_cryptor_set_enabled(self) -> global___FrameCryptorSetEnabledResponse: ...
    @property
    def key_provider_set_key(self) -> global___KeyProviderSetKeyResponse: ...
    @property
    def key_provider_rachet_key(self) -> global___KeyProviderRachetKeyResponse: ...
    @property
    def key_provider_export_key(self) -> global___KeyProviderExportKeyResponse: ...
    def __init__(
        self,
        *,
        e2ee_manager_set_enabled: global___E2EEManagerSetEnabledResponse | None = ...,
        e2ee_manager_set_shared_key: global___E2EEManagerSetSharedKeyResponse | None = ...,
        e2ee_manager_get_frame_cryptors: global___E2EEManagerGetFrameCryptorsResponse | None = ...,
        frame_cryptor_set_enabled: global___FrameCryptorSetEnabledResponse | None = ...,
        key_provider_set_key: global___KeyProviderSetKeyResponse | None = ...,
        key_provider_rachet_key: global___KeyProviderRachetKeyResponse | None = ...,
        key_provider_export_key: global___KeyProviderExportKeyResponse | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["e2ee_manager_get_frame_cryptors", b"e2ee_manager_get_frame_cryptors", "e2ee_manager_set_enabled", b"e2ee_manager_set_enabled", "e2ee_manager_set_shared_key", b"e2ee_manager_set_shared_key", "frame_cryptor_set_enabled", b"frame_cryptor_set_enabled", "key_provider_export_key", b"key_provider_export_key", "key_provider_rachet_key", b"key_provider_rachet_key", "key_provider_set_key", b"key_provider_set_key", "message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["e2ee_manager_get_frame_cryptors", b"e2ee_manager_get_frame_cryptors", "e2ee_manager_set_enabled", b"e2ee_manager_set_enabled", "e2ee_manager_set_shared_key", b"e2ee_manager_set_shared_key", "frame_cryptor_set_enabled", b"frame_cryptor_set_enabled", "key_provider_export_key", b"key_provider_export_key", "key_provider_rachet_key", b"key_provider_rachet_key", "key_provider_set_key", b"key_provider_set_key", "message", b"message"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["message", b"message"]) -> typing_extensions.Literal["e2ee_manager_set_enabled", "e2ee_manager_set_shared_key", "e2ee_manager_get_frame_cryptors", "frame_cryptor_set_enabled", "key_provider_set_key", "key_provider_rachet_key", "key_provider_export_key"] | None: ...

global___E2EEResponse = E2EEResponse
