"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import handle_pb2
import participant_pb2
import sys
import track_pb2
import typing
import video_frame_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ConnectionQuality:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ConnectionQualityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ConnectionQuality.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    QUALITY_POOR: _ConnectionQuality.ValueType  # 0
    QUALITY_GOOD: _ConnectionQuality.ValueType  # 1
    QUALITY_EXCELLENT: _ConnectionQuality.ValueType  # 2

class ConnectionQuality(_ConnectionQuality, metaclass=_ConnectionQualityEnumTypeWrapper):
    """/
    / Room
    /
    """

QUALITY_POOR: ConnectionQuality.ValueType  # 0
QUALITY_GOOD: ConnectionQuality.ValueType  # 1
QUALITY_EXCELLENT: ConnectionQuality.ValueType  # 2
global___ConnectionQuality = ConnectionQuality

class _ConnectionState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ConnectionStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ConnectionState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CONN_DISCONNECTED: _ConnectionState.ValueType  # 0
    CONN_CONNECTED: _ConnectionState.ValueType  # 1
    CONN_RECONNECTING: _ConnectionState.ValueType  # 2

class ConnectionState(_ConnectionState, metaclass=_ConnectionStateEnumTypeWrapper): ...

CONN_DISCONNECTED: ConnectionState.ValueType  # 0
CONN_CONNECTED: ConnectionState.ValueType  # 1
CONN_RECONNECTING: ConnectionState.ValueType  # 2
global___ConnectionState = ConnectionState

class _DataPacketKind:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DataPacketKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DataPacketKind.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    KIND_LOSSY: _DataPacketKind.ValueType  # 0
    KIND_RELIABLE: _DataPacketKind.ValueType  # 1

class DataPacketKind(_DataPacketKind, metaclass=_DataPacketKindEnumTypeWrapper): ...

KIND_LOSSY: DataPacketKind.ValueType  # 0
KIND_RELIABLE: DataPacketKind.ValueType  # 1
global___DataPacketKind = DataPacketKind

@typing_extensions.final
class ConnectRequest(google.protobuf.message.Message):
    """Connect to a new LiveKit room"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    url: builtins.str
    token: builtins.str
    @property
    def options(self) -> global___RoomOptions: ...
    def __init__(
        self,
        *,
        url: builtins.str = ...,
        token: builtins.str = ...,
        options: global___RoomOptions | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["options", b"options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["options", b"options", "token", b"token", "url", b"url"]) -> None: ...

global___ConnectRequest = ConnectRequest

@typing_extensions.final
class ConnectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    @property
    def async_id(self) -> handle_pb2.FfiAsyncId: ...
    def __init__(
        self,
        *,
        async_id: handle_pb2.FfiAsyncId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> None: ...

global___ConnectResponse = ConnectResponse

@typing_extensions.final
class ConnectCallback(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    ROOM_FIELD_NUMBER: builtins.int
    @property
    def async_id(self) -> handle_pb2.FfiAsyncId: ...
    error: builtins.str
    @property
    def room(self) -> global___RoomInfo: ...
    def __init__(
        self,
        *,
        async_id: handle_pb2.FfiAsyncId | None = ...,
        error: builtins.str | None = ...,
        room: global___RoomInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_error", b"_error", "async_id", b"async_id", "error", b"error", "room", b"room"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_error", b"_error", "async_id", b"async_id", "error", b"error", "room", b"room"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_error", b"_error"]) -> typing_extensions.Literal["error"] | None: ...

global___ConnectCallback = ConnectCallback

@typing_extensions.final
class DisconnectRequest(google.protobuf.message.Message):
    """Disconnect from the a room"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    @property
    def room_handle(self) -> handle_pb2.FfiHandleId: ...
    def __init__(
        self,
        *,
        room_handle: handle_pb2.FfiHandleId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["room_handle", b"room_handle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["room_handle", b"room_handle"]) -> None: ...

global___DisconnectRequest = DisconnectRequest

@typing_extensions.final
class DisconnectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    @property
    def async_id(self) -> handle_pb2.FfiAsyncId: ...
    def __init__(
        self,
        *,
        async_id: handle_pb2.FfiAsyncId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> None: ...

global___DisconnectResponse = DisconnectResponse

@typing_extensions.final
class DisconnectCallback(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    @property
    def async_id(self) -> handle_pb2.FfiAsyncId: ...
    def __init__(
        self,
        *,
        async_id: handle_pb2.FfiAsyncId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> None: ...

global___DisconnectCallback = DisconnectCallback

@typing_extensions.final
class PublishTrackRequest(google.protobuf.message.Message):
    """Publish a track to the room"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    TRACK_HANDLE_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    @property
    def room_handle(self) -> handle_pb2.FfiHandleId: ...
    @property
    def track_handle(self) -> handle_pb2.FfiHandleId: ...
    @property
    def options(self) -> global___TrackPublishOptions: ...
    def __init__(
        self,
        *,
        room_handle: handle_pb2.FfiHandleId | None = ...,
        track_handle: handle_pb2.FfiHandleId | None = ...,
        options: global___TrackPublishOptions | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["options", b"options", "room_handle", b"room_handle", "track_handle", b"track_handle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["options", b"options", "room_handle", b"room_handle", "track_handle", b"track_handle"]) -> None: ...

global___PublishTrackRequest = PublishTrackRequest

@typing_extensions.final
class PublishTrackResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    @property
    def async_id(self) -> handle_pb2.FfiAsyncId: ...
    def __init__(
        self,
        *,
        async_id: handle_pb2.FfiAsyncId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> None: ...

global___PublishTrackResponse = PublishTrackResponse

@typing_extensions.final
class PublishTrackCallback(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    PUBLICATION_FIELD_NUMBER: builtins.int
    @property
    def async_id(self) -> handle_pb2.FfiAsyncId: ...
    error: builtins.str
    @property
    def publication(self) -> track_pb2.TrackPublicationInfo: ...
    def __init__(
        self,
        *,
        async_id: handle_pb2.FfiAsyncId | None = ...,
        error: builtins.str | None = ...,
        publication: track_pb2.TrackPublicationInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_error", b"_error", "async_id", b"async_id", "error", b"error", "publication", b"publication"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_error", b"_error", "async_id", b"async_id", "error", b"error", "publication", b"publication"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_error", b"_error"]) -> typing_extensions.Literal["error"] | None: ...

global___PublishTrackCallback = PublishTrackCallback

@typing_extensions.final
class UnpublishTrackRequest(google.protobuf.message.Message):
    """Unpublish a track from the room"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    TRACK_SID_FIELD_NUMBER: builtins.int
    STOP_ON_UNPUBLISH_FIELD_NUMBER: builtins.int
    @property
    def room_handle(self) -> handle_pb2.FfiHandleId: ...
    track_sid: builtins.str
    stop_on_unpublish: builtins.bool
    def __init__(
        self,
        *,
        room_handle: handle_pb2.FfiHandleId | None = ...,
        track_sid: builtins.str = ...,
        stop_on_unpublish: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["room_handle", b"room_handle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["room_handle", b"room_handle", "stop_on_unpublish", b"stop_on_unpublish", "track_sid", b"track_sid"]) -> None: ...

global___UnpublishTrackRequest = UnpublishTrackRequest

@typing_extensions.final
class UnpublishTrackResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    @property
    def async_id(self) -> handle_pb2.FfiAsyncId: ...
    def __init__(
        self,
        *,
        async_id: handle_pb2.FfiAsyncId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> None: ...

global___UnpublishTrackResponse = UnpublishTrackResponse

@typing_extensions.final
class UnpublishTrackCallback(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def async_id(self) -> handle_pb2.FfiAsyncId: ...
    error: builtins.str
    def __init__(
        self,
        *,
        async_id: handle_pb2.FfiAsyncId | None = ...,
        error: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_error", b"_error", "async_id", b"async_id", "error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_error", b"_error", "async_id", b"async_id", "error", b"error"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_error", b"_error"]) -> typing_extensions.Literal["error"] | None: ...

global___UnpublishTrackCallback = UnpublishTrackCallback

@typing_extensions.final
class PublishDataRequest(google.protobuf.message.Message):
    """Publish data to other participants"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    DATA_PTR_FIELD_NUMBER: builtins.int
    DATA_SIZE_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    DESTINATION_SIDS_FIELD_NUMBER: builtins.int
    @property
    def room_handle(self) -> handle_pb2.FfiHandleId: ...
    data_ptr: builtins.int
    data_size: builtins.int
    kind: global___DataPacketKind.ValueType
    @property
    def destination_sids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """destination"""
    def __init__(
        self,
        *,
        room_handle: handle_pb2.FfiHandleId | None = ...,
        data_ptr: builtins.int = ...,
        data_size: builtins.int = ...,
        kind: global___DataPacketKind.ValueType = ...,
        destination_sids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["room_handle", b"room_handle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data_ptr", b"data_ptr", "data_size", b"data_size", "destination_sids", b"destination_sids", "kind", b"kind", "room_handle", b"room_handle"]) -> None: ...

global___PublishDataRequest = PublishDataRequest

@typing_extensions.final
class PublishDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    @property
    def async_id(self) -> handle_pb2.FfiAsyncId: ...
    def __init__(
        self,
        *,
        async_id: handle_pb2.FfiAsyncId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["async_id", b"async_id"]) -> None: ...

global___PublishDataResponse = PublishDataResponse

@typing_extensions.final
class PublishDataCallback(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ASYNC_ID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def async_id(self) -> handle_pb2.FfiAsyncId: ...
    error: builtins.str
    def __init__(
        self,
        *,
        async_id: handle_pb2.FfiAsyncId | None = ...,
        error: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_error", b"_error", "async_id", b"async_id", "error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_error", b"_error", "async_id", b"async_id", "error", b"error"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_error", b"_error"]) -> typing_extensions.Literal["error"] | None: ...

global___PublishDataCallback = PublishDataCallback

@typing_extensions.final
class SetSubscribedRequest(google.protobuf.message.Message):
    """Change the "desire" to subscribe to a track"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    SUBSCRIBE_FIELD_NUMBER: builtins.int
    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    TRACK_SID_FIELD_NUMBER: builtins.int
    @property
    def room_handle(self) -> handle_pb2.FfiHandleId: ...
    subscribe: builtins.bool
    participant_sid: builtins.str
    track_sid: builtins.str
    def __init__(
        self,
        *,
        room_handle: handle_pb2.FfiHandleId | None = ...,
        subscribe: builtins.bool = ...,
        participant_sid: builtins.str = ...,
        track_sid: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["room_handle", b"room_handle"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["participant_sid", b"participant_sid", "room_handle", b"room_handle", "subscribe", b"subscribe", "track_sid", b"track_sid"]) -> None: ...

global___SetSubscribedRequest = SetSubscribedRequest

@typing_extensions.final
class SetSubscribedResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SetSubscribedResponse = SetSubscribedResponse

@typing_extensions.final
class VideoEncoding(google.protobuf.message.Message):
    """/
    / Options
    /
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAX_BITRATE_FIELD_NUMBER: builtins.int
    MAX_FRAMERATE_FIELD_NUMBER: builtins.int
    max_bitrate: builtins.int
    max_framerate: builtins.float
    def __init__(
        self,
        *,
        max_bitrate: builtins.int = ...,
        max_framerate: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["max_bitrate", b"max_bitrate", "max_framerate", b"max_framerate"]) -> None: ...

global___VideoEncoding = VideoEncoding

@typing_extensions.final
class AudioEncoding(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAX_BITRATE_FIELD_NUMBER: builtins.int
    max_bitrate: builtins.int
    def __init__(
        self,
        *,
        max_bitrate: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["max_bitrate", b"max_bitrate"]) -> None: ...

global___AudioEncoding = AudioEncoding

@typing_extensions.final
class TrackPublishOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIDEO_ENCODING_FIELD_NUMBER: builtins.int
    AUDIO_ENCODING_FIELD_NUMBER: builtins.int
    VIDEO_CODEC_FIELD_NUMBER: builtins.int
    DTX_FIELD_NUMBER: builtins.int
    RED_FIELD_NUMBER: builtins.int
    SIMULCAST_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    @property
    def video_encoding(self) -> global___VideoEncoding:
        """encodings are optional"""
    @property
    def audio_encoding(self) -> global___AudioEncoding: ...
    video_codec: video_frame_pb2.VideoCodec.ValueType
    dtx: builtins.bool
    red: builtins.bool
    simulcast: builtins.bool
    source: track_pb2.TrackSource.ValueType
    def __init__(
        self,
        *,
        video_encoding: global___VideoEncoding | None = ...,
        audio_encoding: global___AudioEncoding | None = ...,
        video_codec: video_frame_pb2.VideoCodec.ValueType = ...,
        dtx: builtins.bool = ...,
        red: builtins.bool = ...,
        simulcast: builtins.bool = ...,
        source: track_pb2.TrackSource.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["audio_encoding", b"audio_encoding", "video_encoding", b"video_encoding"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["audio_encoding", b"audio_encoding", "dtx", b"dtx", "red", b"red", "simulcast", b"simulcast", "source", b"source", "video_codec", b"video_codec", "video_encoding", b"video_encoding"]) -> None: ...

global___TrackPublishOptions = TrackPublishOptions

@typing_extensions.final
class RoomOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTO_SUBSCRIBE_FIELD_NUMBER: builtins.int
    ADAPTIVE_STREAM_FIELD_NUMBER: builtins.int
    DYNACAST_FIELD_NUMBER: builtins.int
    auto_subscribe: builtins.bool
    adaptive_stream: builtins.bool
    dynacast: builtins.bool
    def __init__(
        self,
        *,
        auto_subscribe: builtins.bool = ...,
        adaptive_stream: builtins.bool = ...,
        dynacast: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["adaptive_stream", b"adaptive_stream", "auto_subscribe", b"auto_subscribe", "dynacast", b"dynacast"]) -> None: ...

global___RoomOptions = RoomOptions

@typing_extensions.final
class RoomEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROOM_HANDLE_FIELD_NUMBER: builtins.int
    PARTICIPANT_CONNECTED_FIELD_NUMBER: builtins.int
    PARTICIPANT_DISCONNECTED_FIELD_NUMBER: builtins.int
    LOCAL_TRACK_PUBLISHED_FIELD_NUMBER: builtins.int
    LOCAL_TRACK_UNPUBLISHED_FIELD_NUMBER: builtins.int
    TRACK_PUBLISHED_FIELD_NUMBER: builtins.int
    TRACK_UNPUBLISHED_FIELD_NUMBER: builtins.int
    TRACK_SUBSCRIBED_FIELD_NUMBER: builtins.int
    TRACK_UNSUBSCRIBED_FIELD_NUMBER: builtins.int
    TRACK_SUBSCRIPTION_FAILED_FIELD_NUMBER: builtins.int
    TRACK_MUTED_FIELD_NUMBER: builtins.int
    TRACK_UNMUTED_FIELD_NUMBER: builtins.int
    ACTIVE_SPEAKERS_CHANGED_FIELD_NUMBER: builtins.int
    CONNECTION_QUALITY_CHANGED_FIELD_NUMBER: builtins.int
    DATA_RECEIVED_FIELD_NUMBER: builtins.int
    CONNECTION_STATE_CHANGED_FIELD_NUMBER: builtins.int
    CONNECTED_FIELD_NUMBER: builtins.int
    DISCONNECTED_FIELD_NUMBER: builtins.int
    RECONNECTING_FIELD_NUMBER: builtins.int
    RECONNECTED_FIELD_NUMBER: builtins.int
    @property
    def room_handle(self) -> handle_pb2.FfiHandleId: ...
    @property
    def participant_connected(self) -> global___ParticipantConnected: ...
    @property
    def participant_disconnected(self) -> global___ParticipantDisconnected: ...
    @property
    def local_track_published(self) -> global___LocalTrackPublished: ...
    @property
    def local_track_unpublished(self) -> global___LocalTrackUnpublished: ...
    @property
    def track_published(self) -> global___TrackPublished: ...
    @property
    def track_unpublished(self) -> global___TrackUnpublished: ...
    @property
    def track_subscribed(self) -> global___TrackSubscribed: ...
    @property
    def track_unsubscribed(self) -> global___TrackUnsubscribed: ...
    @property
    def track_subscription_failed(self) -> global___TrackSubscriptionFailed: ...
    @property
    def track_muted(self) -> global___TrackMuted: ...
    @property
    def track_unmuted(self) -> global___TrackUnmuted: ...
    @property
    def active_speakers_changed(self) -> global___ActiveSpeakersChanged: ...
    @property
    def connection_quality_changed(self) -> global___ConnectionQualityChanged: ...
    @property
    def data_received(self) -> global___DataReceived: ...
    @property
    def connection_state_changed(self) -> global___ConnectionStateChanged: ...
    @property
    def connected(self) -> global___Connected: ...
    @property
    def disconnected(self) -> global___Disconnected: ...
    @property
    def reconnecting(self) -> global___Reconnecting: ...
    @property
    def reconnected(self) -> global___Reconnected: ...
    def __init__(
        self,
        *,
        room_handle: handle_pb2.FfiHandleId | None = ...,
        participant_connected: global___ParticipantConnected | None = ...,
        participant_disconnected: global___ParticipantDisconnected | None = ...,
        local_track_published: global___LocalTrackPublished | None = ...,
        local_track_unpublished: global___LocalTrackUnpublished | None = ...,
        track_published: global___TrackPublished | None = ...,
        track_unpublished: global___TrackUnpublished | None = ...,
        track_subscribed: global___TrackSubscribed | None = ...,
        track_unsubscribed: global___TrackUnsubscribed | None = ...,
        track_subscription_failed: global___TrackSubscriptionFailed | None = ...,
        track_muted: global___TrackMuted | None = ...,
        track_unmuted: global___TrackUnmuted | None = ...,
        active_speakers_changed: global___ActiveSpeakersChanged | None = ...,
        connection_quality_changed: global___ConnectionQualityChanged | None = ...,
        data_received: global___DataReceived | None = ...,
        connection_state_changed: global___ConnectionStateChanged | None = ...,
        connected: global___Connected | None = ...,
        disconnected: global___Disconnected | None = ...,
        reconnecting: global___Reconnecting | None = ...,
        reconnected: global___Reconnected | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["active_speakers_changed", b"active_speakers_changed", "connected", b"connected", "connection_quality_changed", b"connection_quality_changed", "connection_state_changed", b"connection_state_changed", "data_received", b"data_received", "disconnected", b"disconnected", "local_track_published", b"local_track_published", "local_track_unpublished", b"local_track_unpublished", "message", b"message", "participant_connected", b"participant_connected", "participant_disconnected", b"participant_disconnected", "reconnected", b"reconnected", "reconnecting", b"reconnecting", "room_handle", b"room_handle", "track_muted", b"track_muted", "track_published", b"track_published", "track_subscribed", b"track_subscribed", "track_subscription_failed", b"track_subscription_failed", "track_unmuted", b"track_unmuted", "track_unpublished", b"track_unpublished", "track_unsubscribed", b"track_unsubscribed"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["active_speakers_changed", b"active_speakers_changed", "connected", b"connected", "connection_quality_changed", b"connection_quality_changed", "connection_state_changed", b"connection_state_changed", "data_received", b"data_received", "disconnected", b"disconnected", "local_track_published", b"local_track_published", "local_track_unpublished", b"local_track_unpublished", "message", b"message", "participant_connected", b"participant_connected", "participant_disconnected", b"participant_disconnected", "reconnected", b"reconnected", "reconnecting", b"reconnecting", "room_handle", b"room_handle", "track_muted", b"track_muted", "track_published", b"track_published", "track_subscribed", b"track_subscribed", "track_subscription_failed", b"track_subscription_failed", "track_unmuted", b"track_unmuted", "track_unpublished", b"track_unpublished", "track_unsubscribed", b"track_unsubscribed"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["message", b"message"]) -> typing_extensions.Literal["participant_connected", "participant_disconnected", "local_track_published", "local_track_unpublished", "track_published", "track_unpublished", "track_subscribed", "track_unsubscribed", "track_subscription_failed", "track_muted", "track_unmuted", "active_speakers_changed", "connection_quality_changed", "data_received", "connection_state_changed", "connected", "disconnected", "reconnecting", "reconnected"] | None: ...

global___RoomEvent = RoomEvent

@typing_extensions.final
class RoomInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    SID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    LOCAL_PARTICIPANT_FIELD_NUMBER: builtins.int
    PARTICIPANTS_FIELD_NUMBER: builtins.int
    @property
    def handle(self) -> handle_pb2.FfiHandleId: ...
    sid: builtins.str
    name: builtins.str
    metadata: builtins.str
    @property
    def local_participant(self) -> participant_pb2.ParticipantInfo: ...
    @property
    def participants(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[participant_pb2.ParticipantInfo]: ...
    def __init__(
        self,
        *,
        handle: handle_pb2.FfiHandleId | None = ...,
        sid: builtins.str = ...,
        name: builtins.str = ...,
        metadata: builtins.str = ...,
        local_participant: participant_pb2.ParticipantInfo | None = ...,
        participants: collections.abc.Iterable[participant_pb2.ParticipantInfo] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["handle", b"handle", "local_participant", b"local_participant"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["handle", b"handle", "local_participant", b"local_participant", "metadata", b"metadata", "name", b"name", "participants", b"participants", "sid", b"sid"]) -> None: ...

global___RoomInfo = RoomInfo

@typing_extensions.final
class ParticipantConnected(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> participant_pb2.ParticipantInfo: ...
    def __init__(
        self,
        *,
        info: participant_pb2.ParticipantInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["info", b"info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["info", b"info"]) -> None: ...

global___ParticipantConnected = ParticipantConnected

@typing_extensions.final
class ParticipantDisconnected(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    @property
    def info(self) -> participant_pb2.ParticipantInfo: ...
    def __init__(
        self,
        *,
        info: participant_pb2.ParticipantInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["info", b"info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["info", b"info"]) -> None: ...

global___ParticipantDisconnected = ParticipantDisconnected

@typing_extensions.final
class LocalTrackPublished(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLICATION_FIELD_NUMBER: builtins.int
    TRACK_FIELD_NUMBER: builtins.int
    @property
    def publication(self) -> track_pb2.TrackPublicationInfo: ...
    @property
    def track(self) -> track_pb2.TrackInfo: ...
    def __init__(
        self,
        *,
        publication: track_pb2.TrackPublicationInfo | None = ...,
        track: track_pb2.TrackInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["publication", b"publication", "track", b"track"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["publication", b"publication", "track", b"track"]) -> None: ...

global___LocalTrackPublished = LocalTrackPublished

@typing_extensions.final
class LocalTrackUnpublished(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLICATION_SID_FIELD_NUMBER: builtins.int
    publication_sid: builtins.str
    def __init__(
        self,
        *,
        publication_sid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["publication_sid", b"publication_sid"]) -> None: ...

global___LocalTrackUnpublished = LocalTrackUnpublished

@typing_extensions.final
class TrackPublished(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    PUBLICATION_FIELD_NUMBER: builtins.int
    participant_sid: builtins.str
    @property
    def publication(self) -> track_pb2.TrackPublicationInfo: ...
    def __init__(
        self,
        *,
        participant_sid: builtins.str = ...,
        publication: track_pb2.TrackPublicationInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["publication", b"publication"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["participant_sid", b"participant_sid", "publication", b"publication"]) -> None: ...

global___TrackPublished = TrackPublished

@typing_extensions.final
class TrackUnpublished(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    PUBLICATION_SID_FIELD_NUMBER: builtins.int
    participant_sid: builtins.str
    publication_sid: builtins.str
    def __init__(
        self,
        *,
        participant_sid: builtins.str = ...,
        publication_sid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["participant_sid", b"participant_sid", "publication_sid", b"publication_sid"]) -> None: ...

global___TrackUnpublished = TrackUnpublished

@typing_extensions.final
class TrackSubscribed(google.protobuf.message.Message):
    """Publication isn't needed for subscription events on the FFI
    The FFI will retrieve the publication using the Track sid
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    TRACK_FIELD_NUMBER: builtins.int
    participant_sid: builtins.str
    @property
    def track(self) -> track_pb2.TrackInfo: ...
    def __init__(
        self,
        *,
        participant_sid: builtins.str = ...,
        track: track_pb2.TrackInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["track", b"track"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["participant_sid", b"participant_sid", "track", b"track"]) -> None: ...

global___TrackSubscribed = TrackSubscribed

@typing_extensions.final
class TrackUnsubscribed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    TRACK_SID_FIELD_NUMBER: builtins.int
    participant_sid: builtins.str
    """The FFI language can dispose/remove the VideoSink here"""
    track_sid: builtins.str
    def __init__(
        self,
        *,
        participant_sid: builtins.str = ...,
        track_sid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["participant_sid", b"participant_sid", "track_sid", b"track_sid"]) -> None: ...

global___TrackUnsubscribed = TrackUnsubscribed

@typing_extensions.final
class TrackSubscriptionFailed(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    TRACK_SID_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    participant_sid: builtins.str
    track_sid: builtins.str
    error: builtins.str
    def __init__(
        self,
        *,
        participant_sid: builtins.str = ...,
        track_sid: builtins.str = ...,
        error: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "participant_sid", b"participant_sid", "track_sid", b"track_sid"]) -> None: ...

global___TrackSubscriptionFailed = TrackSubscriptionFailed

@typing_extensions.final
class TrackMuted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    TRACK_SID_FIELD_NUMBER: builtins.int
    participant_sid: builtins.str
    track_sid: builtins.str
    def __init__(
        self,
        *,
        participant_sid: builtins.str = ...,
        track_sid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["participant_sid", b"participant_sid", "track_sid", b"track_sid"]) -> None: ...

global___TrackMuted = TrackMuted

@typing_extensions.final
class TrackUnmuted(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    TRACK_SID_FIELD_NUMBER: builtins.int
    participant_sid: builtins.str
    track_sid: builtins.str
    def __init__(
        self,
        *,
        participant_sid: builtins.str = ...,
        track_sid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["participant_sid", b"participant_sid", "track_sid", b"track_sid"]) -> None: ...

global___TrackUnmuted = TrackUnmuted

@typing_extensions.final
class ActiveSpeakersChanged(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SIDS_FIELD_NUMBER: builtins.int
    @property
    def participant_sids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        participant_sids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["participant_sids", b"participant_sids"]) -> None: ...

global___ActiveSpeakersChanged = ActiveSpeakersChanged

@typing_extensions.final
class ConnectionQualityChanged(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    QUALITY_FIELD_NUMBER: builtins.int
    participant_sid: builtins.str
    quality: global___ConnectionQuality.ValueType
    def __init__(
        self,
        *,
        participant_sid: builtins.str = ...,
        quality: global___ConnectionQuality.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["participant_sid", b"participant_sid", "quality", b"quality"]) -> None: ...

global___ConnectionQualityChanged = ConnectionQualityChanged

@typing_extensions.final
class DataReceived(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HANDLE_FIELD_NUMBER: builtins.int
    PARTICIPANT_SID_FIELD_NUMBER: builtins.int
    DATA_PTR_FIELD_NUMBER: builtins.int
    DATA_SIZE_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    @property
    def handle(self) -> handle_pb2.FfiHandleId: ...
    participant_sid: builtins.str
    """Can be empty if the data is sent a server SDK"""
    data_ptr: builtins.int
    data_size: builtins.int
    kind: global___DataPacketKind.ValueType
    def __init__(
        self,
        *,
        handle: handle_pb2.FfiHandleId | None = ...,
        participant_sid: builtins.str | None = ...,
        data_ptr: builtins.int = ...,
        data_size: builtins.int = ...,
        kind: global___DataPacketKind.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_participant_sid", b"_participant_sid", "handle", b"handle", "participant_sid", b"participant_sid"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_participant_sid", b"_participant_sid", "data_ptr", b"data_ptr", "data_size", b"data_size", "handle", b"handle", "kind", b"kind", "participant_sid", b"participant_sid"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_participant_sid", b"_participant_sid"]) -> typing_extensions.Literal["participant_sid"] | None: ...

global___DataReceived = DataReceived

@typing_extensions.final
class ConnectionStateChanged(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATE_FIELD_NUMBER: builtins.int
    state: global___ConnectionState.ValueType
    def __init__(
        self,
        *,
        state: global___ConnectionState.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["state", b"state"]) -> None: ...

global___ConnectionStateChanged = ConnectionStateChanged

@typing_extensions.final
class Connected(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Connected = Connected

@typing_extensions.final
class Disconnected(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Disconnected = Disconnected

@typing_extensions.final
class Reconnecting(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Reconnecting = Reconnecting

@typing_extensions.final
class Reconnected(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Reconnected = Reconnected
