name: Build API

on:
  push:
    branches:
      - main
    paths:
      - livekit-api/**
    tags:
      - "api-v*.*.*"
  pull_request:
    branches:
      - main
    paths:
      - livekit-api/**
  workflow_dispatch:

env:
  PACKAGE_DIR: ./livekit-api

jobs:
  build_wheels:
    name: Build API wheel/sdist
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_DIR }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v4

      - name: Build wheel & sdist
        run: |
          pip3 install build wheel
          python3 -m build --wheel --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: api-release
          path: |
            livekit-api/dist/*.whl
            livekit-api/dist/*.tar.gz

  publish:
    name: Publish API release
    needs: build_wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: startsWith(github.ref, 'refs/tags/api-v') && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false)
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: api-release
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1

  docs:
    needs: [publish]
    uses: ./.github/workflows/build-docs.yml
    with:
      package_dir: "livekit-api"
      package_name: "livekit.api"
    secrets: inherit
