name: Build Docs

on:
  workflow_dispatch:
    inputs:
      package_dir:
        required: true
        type: string
      package_name:
        required: true
        type: string
      test:
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      package_dir:
        required: true
        type: string
      package_name:
        required: true
        type: string
    secrets:
      PYPI_API_TOKEN:
        required: true
      DOCS_DEPLOY_AWS_ACCESS_KEY:
        required: true
      DOCS_DEPLOY_AWS_API_SECRET:
        required: true

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Package to Document
        env:
          PACKAGE_DIR: ${{ inputs.package_dir }}
        run: python -m pip install "$PACKAGE_DIR/"

      - name: Download ffi
        env:
          PACKAGE_NAME: ${{ inputs.package_name }}
        run: |
          if [[ "$PACKAGE_NAME" = 'livekit.rtc' ]]; then
            pip install requests
            python livekit-rtc/rust-sdks/download_ffi.py --output "$(python -m site --user-site)/livekit/rtc/resources"
          fi

      - name: Install pdoc
        run: pip install --upgrade pdoc

      - name: Build Docs
        env:
          PACKAGE_NAME: ${{ inputs.package_name }}
        run: python -m pdoc "$PACKAGE_NAME" --docformat=google --output-dir docs

      - name: S3 Upload
        env:
          PACKAGE_DIR: ${{ inputs.package_dir }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_DEPLOY_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_DEPLOY_AWS_API_SECRET }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: aws s3 cp docs/ "s3://livekit-docs/$PACKAGE_DIR" --recursive
