name: Build API

on:
  push:
    branches:
      - main
    paths:
      - livekit-api/**
    tags:
      - "api-v*.*.*"
  pull_request:
    branches:
      - main
    paths:
      - livekit-api/**
  workflow_dispatch:

env:
  PACKAGE_DIR: ./livekit-api

jobs:
  build_wheels:
    name: Build API wheel/sdist
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_DIR }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: true

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6

      - name: Build wheel & sdist
        run: |
          pip3 install build wheel
          python3 -m build --wheel --sdist

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: api-release
          path: |
            livekit-api/dist/*.whl
            livekit-api/dist/*.tar.gz

  publish:
    name: Publish API release
    needs: build_wheels
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: startsWith(github.ref, 'refs/tags/api-v') && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false)
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: api-release
          path: dist

      - uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # release/v1

  docs:
    needs: [publish]
    uses: ./.github/workflows/build-docs.yml
    with:
      package_dir: "livekit-api"
      package_name: "livekit.api"
    secrets: inherit
