name: Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # wheels to build:
        include:
          - os: ubuntu-latest
            archs: x86_64
          - os: buildjet-4vcpu-ubuntu-2204-arm
            archs: aarch64
          - os: windows-latest
            archs: AMD64 ARM64
          - os: macos-latest
            archs: x86_64 arm64

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_ARCHS: ${{ matrix.archs }}

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.whl